spring:
  application.name: datanet-spring
  datasource:
    url: jdbc:mariadb://ec2-13-125-252-10.ap-northeast-2.compute.amazonaws.com:3306/datanet
    username: admin
    password: test1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true